services:
  web:
    build: .
  nginx:
    ports:
      - "8000:8000"
      - "8443:8443"
    image: "nginx"
    volumes:
      - type: bind
        source: ./nginx/appstreammanager.conf
        target: /etc/nginx/conf.d/appstreammanager.conf
      - type: bind
        source: ./ssl
        target: /etc/nginx/ssl
